apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
patchesStrategicMerge:
  - replica-patch.yml
  - image-tag-patch.yml
  - request-patch.yml
  - limit-patch.yml
