apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization  
resources:
    - statefulset.yml
    - service.yml
    - serviceaccount.yml
    - storageclass.yml
    - externalsecret.yml
    - secretstore.yml
    - serviceaccount2.yml
    - serviceaccount3.yml

