apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secretstore
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secret-operator
            namespace: external-secrets 