apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  template:
    spec:
      containers:
      - name: nodejs
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"